CREATE TABLE disciplina (
  id INT NOT NULL AUTO_INCREMENT,
  nome VARCHAR(255) NOT NULL,
  curso VARCHAR(255) NOT NULL,
  turma VARCHAR(255) NOT NULL,
  local VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);